spring:
  datasource:
    name: freetrip
    url: jdbc:mysql://localhost:3306/freetrip
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.freetrip_banked.bean

