spring:
  datasource:
    name: RUNOOB
    url: jdbc:mysql://localhost:3306/RUNOOB
    username: root
    password: mysqlsql123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.freetrip_banked.bean