spring:
  datasource:
    name: news
    url: jdbc:mysql://localhost:3306/news
    username: root
    password: hxh010203
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.freetrip_banked.bean